#ifndef PLUGININTERFACEREGISTRATION_GLOBAL_H
#define PLUGININTERFACEREGISTRATION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PLUGININTERFACEREGISTRATION_LIBRARY)
#  define PLUGININTERFACEREGISTRATION_EXPORT Q_DECL_EXPORT
#else
#  define PLUGININTERFACEREGISTRATION_EXPORT Q_DECL_IMPORT
#endif

#endif // PLUGININTERFACEREGISTRATION_GLOBAL_H
